### ISSUE TITLE
Graphs generate in only black

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#1105]
1. Create a graph
2. See that it is Black
3. Fix that

**Comment by aarondr77** [comment]
In Jupyter on Chrome or Safari

**Comment by naterush** [comment]
Note that this requires Streamlit to be installed. If Streamlit is installed, then the default plotly theme is set to `streamlit`, which does funky things with colors so they can get it to match the app. 

The fix for this is simple:
```
import plotly.io as pio
if pio.templates.default == 'streamlit':
    pio.templates.default = 'plotly'
```

Because streamlit updates the default theme when it's imported, you just have to make sure to run this code after importing streamlit -- aka, just before graph generation.
