### ISSUE TITLE
Graph rename Y axis input cutoff

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#1181]
This happens in the cases below:
1. The x axis labels are very long and make the graph component very small (video below)
2. The y axis title is long and takes up the vertical space

I think we should be able to fix this by giving the popup a higher Z-component so that it sits above the toolbar. Or detecting that it is cutoff and having it move to a different location (ie: directly to the right of the center of the y axis title instead of the top of it)

https://github.com/mito-ds/mito/assets/18709905/d49682dd-7d8f-432c-b39d-74724d095e8c

**Comment by naterush** [comment]
This problem is what react's createPortal interface will be really helpful in solving. It allows you to place things at the root of the global stacking context - and it's what we do with dropdowns to make sure they are above everything. 

There's a little bit of work to make this all work, because you need a div that you render the portal too -- can we just use the mito container here? 

Then, it feels like you'd just need to update the placement code to take this new context into account...
