### ISSUE TITLE
One Click ML in Mito

### ISSUE THREAD

**Issue by jake-stack** [mito-ds/mito#172]
**Is your feature request related to a problem? Please describe.**

The simplest possible machine learning capabilities 

**Describe the solution you'd like**

Pycaret is an open source python package that provides ML with minimal code -- using the package in the backend, I think we could provide ML capabilities by just passing in the Mitosheet. Pycaret has function that analyzes the data types and then a second function that runs 10 models on it and compares the results. These two functions could happen behind the scenes. The output is a table, which could be a mitosheet or a just an outputted table. 

If you read this documentation through "compare models" it is basically what I want to do: [Link](https://pycaret.gitbook.io/docs/get-started/quickstart#classification)  Analyze model and prediction would also be nice. 

**Describe alternatives you've considered**

**Additional context**

**Comment by naterush** [comment]
@jake-stack thanks for the feature request! 

I think that this sounds like a pretty cool feature, and also something that deserves to go through the full-product process before we implement it.

A few reasons for this:
1. This feature is a new type of step. That is not a few hours of work, but usually a few days of work to implement (assuming that we have mockups!). As such, it's not really a "do it in a few hours" type of idea.
2. This feature requires real specification to work well! It's big and new and certainly at least needs mockups. Moreover, it would do well with some real data collection from our users (we have feedback on modeling we'd like to integrate).
3. The `pycaret` package is a huge new dependency. See their requirements here: https://github.com/pycaret/pycaret/blob/master/requirements.txt. It's massive, and would introduce a bunch of issues for both us and our enterprise clients as we struggled to deal with it. 

All three of these points are things that are addressed and explored in the full feature specification process, and hence this issue should certainly go through that process rather than just discussion in an issue (this is meant as a bug-tracker, and for much smaller feature requests).

Thoughts on next steps here:
1. Feel free to keep posting stuff like this, and I'll keep giving feedback on it. It'll help me get a better understanding of what you think is valuable, while also allowing you to get a better understanding of what belongs here vs. in the product process.
2. Bring this up with Aaron if you think it's valuable and we should prioritize it! IMO, this is very cool, but I def think we should prioritize robustness, performance, and usability in the next product sprint over new features.
